Add data sets and python file
anas14680/BIOStats-Assignment-3 pull request #1
Opened 2022-02-01 04:51 UTC by anas14680

The file name containing all the code in 'Bio stats assignment.py'.

2022-02-01 05:49 UTC, anas14680 commented
@patrickkwang

2022-02-01 05:50 UTC, anas14680 reviewed
@patrickkwang

2022-02-01 15:51 UTC, patrickkwang requested changes
Excellent job. Very thorough! I wouldn't commit the data files. They are very large and will not be changed, so we generally don't put data into git.

Minor suggestions follow.

2022-02-01 15:51 UTC, patrickkwang commented on Bio stats assignment.py
> +        raise ValueError(f"Arguement gt_lt does not accept the value {gt_lt}")  # O(1)
Nice f-string!

2022-02-01 15:51 UTC, patrickkwang commented on Bio stats assignment.py
> +if __name__ == "__main__":
👍

2022-02-01 15:51 UTC, patrickkwang commented on Bio stats assignment.py
> +from os import lseek
Is this used?

2022-02-01 15:51 UTC, patrickkwang commented on Bio stats assignment.py
> +)
Don't run these directly in the module, or it will happen when you import this module. You should pass these into the functions below as arguments.

2022-02-01 15:51 UTC, patrickkwang commented on Bio stats assignment.py
> +def num_older_than(age: Union[int, float], data: dict[str, list[Any]]) -> int:
Can you be more specific than `data`? I think this is meant to be the patient structure.

2022-02-01 15:51 UTC, patrickkwang commented on Bio stats assignment.py
> +    lab: str, gt_lt: str, value: float, data: dict[str, list[Any]]
I think you need to pass both the labs data and the patient data in here.

2022-02-01 15:51 UTC, patrickkwang commented on Bio stats assignment.py
> +def parse_data(filename: str) -> dict[str, list[Any]]:
I think that currently this will always be a `dict[str, list[str]]`.

2022-02-02 06:44 UTC, anas14680 commented on Bio stats assignment.py
> +    lab: str, gt_lt: str, value: float, data: dict[str, list[Any]]
Sir, the function does check if the patient belongs to the lab, that has been mentioned specified in the argument "lab". Not sure if this is the change requested.

2022-02-02 06:44 UTC, anas14680 commented on Bio stats assignment.py
> +            if (data["LabName"][i] == lab) and (
@patrickkwang  here (lab check).

2022-02-04 02:38 UTC, patrickkwang commented on Bio stats assignment.py
> +    lab: str, gt_lt: str, value: float, data: dict[str, list[Any]]
You're right, we don't need the patient table here.

2022-02-04 02:43 UTC, patrickkwang requested changes
Thanks for addressing those items. I typically only comment on one instance of each issue, so be sure to scan for other instances of e.g. ambiguous variable naming or type hints.

2022-02-04 02:43 UTC, patrickkwang commented on Bio stats assignment.py
> +    lab: str, gt_lt: str, value: float, data: dict[str, list[Any]]
Is this `data` the patients table or labs table? Also clarify the type hint here and below.

2022-02-06 18:23 UTC, patrickkwang approved these changes
🚀

2022-02-08 03:07 UTC, merged