Work part 2
anas14680/BIOStats-Assignment-3 pull request #2
Opened 2022-02-09 08:42 UTC by anas14680

This pull request adds a new functionality to ehr library and also tests them. Some errors found in code after testing have also been corrected. @patrickkwang

2022-02-10 21:05 UTC, patrickkwang requested changes
Nice job! Minor comments.

2022-02-10 21:05 UTC, patrickkwang commented on Bio_stats_assignment.py
> +def patient_age(
I appreciate the thorough comments. The function name could be more informative. In my mind, "patient age" is just their current age...

2022-02-10 21:05 UTC, patrickkwang commented on tests.py
> +    labs_data_test = "/Users/mohammadanas/Desktop/Duke MIDS/Spring 2021\
If you use paths for your machine, no one who clones this repo can run the code. Instead, commit the test data files and make these relative paths.

2022-02-13 20:08 UTC, patrickkwang requested changes

2022-02-13 20:08 UTC, patrickkwang commented on tests.py
> +    assert num_older_than(38, data_columns) == "No information found regarding Age"
Should this be returning a string? Or raising an error?

2022-02-13 20:08 UTC, patrickkwang commented on tests.py
> +        == "No information available on patient with ID:ANNA123"
Should this be returning a string? Or raising an error?

2022-02-17 07:39 UTC, anas14680 commented on Bio_stats_assignment.py
> +        raise KeyError(f"No information found regarding Age")  # O(1)
@patrickkwang  Professor I have changed this from returning strings to raising errors 
Please let me know if there are any other changes required 
Thank you

2022-02-17 07:40 UTC, anas14680 commented on Bio_stats_assignment.py
> +        raise KeyError(f"No information found regarding Age")  # O(1)
These changes have been made through out the python script (in other places ) and the test file

2022-02-19 01:26 UTC, patrickkwang approved these changes

2022-02-21 05:40 UTC, merged