Part 3
anas14680/BIOStats-Assignment-3 pull request #3
Opened 2022-02-24 05:45 UTC by anas14680

Object Orient Structure for EHR Library

2022-02-24 05:55 UTC, anas14680 commented
Dear Professor,
@patrickkwang 
This is the way, I have designed my classes and parse data function. 

The patients data class does exactly what was intended. 

However, given that labs are not unique in the dataset, I created it as such that each attribute of the lab stores a list. For example, if a lab name is "URINALYSIS: RED BLOOD CELLS", the patient ID attribute of this lab's class will store a list of all the patients visiting this lab. If I follow this procedure, I can add 'Sick_patients' function as a method to the lab class.

Please let me know if this is fine, otherwise I can make a unique class for each lab data entry. If this is fine, I can proceed with tests, documentation and type hints.

On the bright side, my parse data function now has O(N) complexity.

2022-02-26 03:25 UTC, patrickkwang requested changes
The patient stuff makes sense. I'm not so sure about `data_dict` for the labs, perhaps because I can't see yet how it will be used. If you are aiming for a `dict[lab_name, list[Lab]]`, that might serve for some of our applications. But I don't think that's what's happening currently.

2022-02-26 03:25 UTC, patrickkwang commented on Ehr_OOP.py
> +    def __repr__(self):
`__repr__` typically produces a detailed string representation. For something this simple, I suspect that you want to overload `__str__` instead.

2022-02-26 03:25 UTC, patrickkwang commented on Ehr_OOP.py
> +        self.patientID = PatientID
PEP8 would have all variable and attribute names begin with a lowercase letter.

2022-02-26 03:25 UTC, patrickkwang commented on Ehr_OOP.py
> +    def __init__(self, PatientID):
Add type hints throughout.

2022-02-26 03:25 UTC, patrickkwang commented on Ehr_OOP.py
> +        self.value.append(lab_info["LabValue"])
Why not add this stuff to the constructor (`__init__`)?

2022-02-26 03:25 UTC, patrickkwang commented on Ehr_OOP.py
> +        self.gender = patientinfo["PatientGender"]
Why not add this stuff to the constructor (`__init__`)?

2022-02-26 03:25 UTC, patrickkwang commented on Ehr_OOP.py
> +                        data_dict[lab_n].store_info(information_dict)
Does this not overwrite the data already in there for another measurement with the same lab name?

2022-02-26 03:25 UTC, patrickkwang commented on Ehr_OOP.py
> +def parse_data(filename, pt_lb):
I'd probably just make separate `parse_patient_data` and `parse_lab_data` functions.

2022-03-08 22:39 UTC, patrickkwang requested changes

2022-03-08 22:39 UTC, patrickkwang commented on Ehr_OOP.py
> +        self.labname: str = Labname  # O(1)
```suggestion
        self.name: str = name  # O(1)
```
We already know that it's a lab...

2022-03-08 22:39 UTC, patrickkwang commented on Ehr_OOP.py
> +        self.patientID: str = PatientID  # O(1)
```suggestion
        self.id: str = id  # O(1)
```

2022-03-08 22:39 UTC, patrickkwang commented on Ehr_OOP.py
> +        self.DOB: datetime = datetime.strptime(DOB, "%Y-%m-%d %H:%M:%S.%f")  # O(2)
```suggestion
        self.dob: datetime = datetime.strptime(dob, "%Y-%m-%d %H:%M:%S.%f")  # O(2)
```
PEP8 style guidance would have variable and attribute names start with a lowercase letter. We typically capitalize acronyms as if they were ordinary words.

2022-03-08 22:39 UTC, patrickkwang commented on Ehr_OOP.py
> +"""Bio stats assignment #OOP Mohammad Anas."""
We can replace the old stuff instead of making a new file.

2022-03-08 22:39 UTC, patrickkwang commented on tests.py
> +    for i, j in zip(answer, test):
You should be able to compare these more concisely. You may want to implement `__eq__()` on your classes.

2022-03-15 00:45 UTC, patrickkwang approved these changes

2022-03-21 22:23 UTC, merged